default_connection_name = "my_test_connection" 
[connections]
[connections.my_test_connection]
account = "esahiuu-tz70369"
user = "pradeep"
password = "Abcd067$"
database = "DEMO_DB"
schema = "PUBLIC"